import type { Metadata, Viewport } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import { PostHogProvider } from './providers'
import { OFFICES, TEAM_SECTION } from '@/data/content';
import './globals.css';

/**
 * Inter for display and body — a grotesque with tight apertures that holds up at
 * 12rem without looking decorative. JetBrains Mono for every piece of
 * instrumentation text (coordinates, bands, model ids), which is what gives the
 * page its scientific register.
 */
const sans = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
  axes: ['opsz'],
});

const mono = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500'],
  variable: '--font-mono',
});

// Social (OG/Twitter) title uses the brand tagline; the SERP <title> leads with
// the primary keyword phrase and gets a "· RASID" suffix on child pages via the
// template. Description trimmed to ~150 chars (was 190 → truncated in SERPs).
const OG_TITLE = 'RASID: Seeing Earth, Smarter';
const DESCRIPTION =
  'GoPilot is RASID’s AI geospatial agent. Ask in plain language and it finds the right satellite data, picks the right models, and returns the answer.';

export const metadata: Metadata = {
  metadataBase: new URL('https://rasid.ai'),
  title: {
    default: 'GoPilot by RASID: AI Geospatial Agent for Earth Data',
    template: '%s · RASID',
  },
  description: DESCRIPTION,
  applicationName: 'RASID',
  // Self-referencing canonical (resolved against metadataBase → https://rasid.ai/).
  // Per-route pages set their own canonical.
  alternates: { canonical: '/' },
  // Favicon / app icons live in public/logo/ (the green R). Declared here since
  // we don't use the app/icon.png file convention.
  icons: {
    icon: '/logo/favicon.png',
    apple: '/logo/apple-touch-icon.png',
  },
  keywords: [
    'geospatial AI',
    'GeoAI',
    'AI geospatial agent',
    'satellite imagery',
    'satellite data',
    'Earth observation',
    'remote sensing',
    'GoPilot',
    'RASID',
    'MCP',
    'QGIS',
    'ArcGIS Pro',
    'change detection',
    'solar detection',
    'field delineation',
  ],
  openGraph: {
    type: 'website',
    siteName: 'RASID',
    locale: 'en_US',
    url: '/',
    title: OG_TITLE,
    description: DESCRIPTION,
    // og:image is generated by app/opengraph-image.tsx (Next auto-injects the tag).
  },
  twitter: {
    card: 'summary_large_image',
    title: OG_TITLE,
    description: DESCRIPTION,
    // twitter:image comes from app/twitter-image.tsx.
  },
  robots: { index: true, follow: true },
};

export const viewport: Viewport = {
  themeColor: '#060C0A',
  colorScheme: 'dark',
  width: 'device-width',
  initialScale: 1,
  // The hero relies on a stable viewport height; allowing zoom is still
  // required for accessibility, so only the initial scale is fixed.
  maximumScale: 5,
};

/* Applies the persisted palette to <html> before first paint, so a non-default
   theme doesn't flash the default on reload. Kept tiny and dependency-free. */
const themeInit = `(function(){try{var t=localStorage.getItem('rasid-theme');if(t&&t!=='dark')document.documentElement.dataset.theme=t;}catch(e){}})();`;

/* Site-wide structured data (one @graph so engines/LLMs build a single coherent
   entity). Organization is the highest-leverage type for an AI-SaaS brand — it's
   how search engines and answer engines attach facts (offices, award, what the
   company knows about) to the RASID entity. WebSite links back to it by @id.
   Page-specific schema (SoftwareApplication, FAQPage, BreadcrumbList) lives on
   the relevant route/component and references #organization by @id. */
const ORG_DESCRIPTION =
  'RASID is a geospatial-AI company that builds GoPilot, an AI agent for Earth observation. GoPilot answers plain-language questions about satellite imagery by finding data, selecting AI models, running the analysis, and returning raster and vector results.';

// Real team members as Person nodes (name + role + LinkedIn), linked to the
// Organization. Concrete E-E-A-T / expertise signal answer engines attach to a
// named team; sourced from the same TEAM_SECTION the site renders.
const people = TEAM_SECTION.members.map((m) => ({
  '@type': 'Person',
  '@id': `https://rasid.ai/#person-${m.initials.toLowerCase()}`,
  name: m.name,
  jobTitle: m.role,
  ...(m.linkedin ? { url: m.linkedin, sameAs: [m.linkedin] } : {}),
  worksFor: { '@id': 'https://rasid.ai/#organization' },
}));

const structuredData = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': 'https://rasid.ai/#organization',
      name: 'RASID',
      url: 'https://rasid.ai',
      logo: {
        '@type': 'ImageObject',
        url: 'https://rasid.ai/logo/manifest-512.png',
        width: 512,
        height: 512,
      },
      description: ORG_DESCRIPTION,
      slogan: 'Seeing Earth, Smarter.',
      email: 'info@rasid.ai',
      knowsAbout: [
        'Geospatial AI',
        'Earth observation',
        'Remote sensing',
        'Satellite imagery analysis',
        'Geographic information systems',
        'Change detection',
      ],
      award: 'Winner, AWS Generative AI Challenge 2026',
      sameAs: [
        'https://www.linkedin.com/company/rasid-ai/',
        'https://www.youtube.com/@RASIDAI',
      ],
      contactPoint: {
        '@type': 'ContactPoint',
        email: 'info@rasid.ai',
        contactType: 'sales',
        availableLanguage: 'English',
      },
      address: OFFICES.map((o) => ({
        '@type': 'PostalAddress',
        streetAddress: o.postal.streetAddress,
        postalCode: o.postal.postalCode,
        addressLocality: o.postal.addressLocality,
        addressCountry: o.postal.addressCountry,
      })),
      employee: people.map((p) => ({ '@id': p['@id'] })),
    },
    {
      '@type': 'WebSite',
      '@id': 'https://rasid.ai/#website',
      url: 'https://rasid.ai',
      name: 'RASID',
      description: ORG_DESCRIPTION,
      inLanguage: 'en',
      publisher: { '@id': 'https://rasid.ai/#organization' },
    },
    ...people,
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable}`} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInit }} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
      </head>
      <body className="bg-void text-chalk">
        <PostHogProvider>  
          {children}  
        </PostHogProvider>  
      </body>
    </html>
  );
}